# Generated by Django 3.0 on 2020-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200103_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexpense',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
