# Generated by Django 3.0 on 2020-01-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200103_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
