# Generated by Django 3.0 on 2020-01-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_invoice_accountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexpense',
            name='date_purchased',
        ),
    ]
