# Generated by Django 3.0 on 2020-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_jobexpense_date_purchased'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['invoiceid']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='name',
            new_name='invoice_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='billed',
            new_name='invoiced',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
    ]
