# Generated by Django 3.0 on 2020-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200114_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
