# Generated by Django 3.0 on 2020-01-26 05:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='crew',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='yard',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, size=4),
        ),
        migrations.AddField(
            model_name='yard',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
