# Generated by Django 3.0 on 2020-01-26 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200125_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), default=list, size=4),
        ),
    ]
