# Generated by Django 3.0 on 2020-01-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200126_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crewid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crew_lead', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-accountid']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoiceid']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-jobid']},
        ),
        migrations.AlterModelOptions(
            name='jobexpense',
            options={'ordering': ['-job_expenseid']},
        ),
        migrations.AlterModelOptions(
            name='yard',
            options={'ordering': ['-yardid']},
        ),
    ]
