# Generated by Django 3.0 on 2020-01-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200126_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_lead',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
