# Generated by Django 3.0 on 2020-01-27 03:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200126_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=6), default=list, size=4),
        ),
    ]
