# Generated by Django 3.0 on 2020-01-27 03:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200126_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='None', max_length=6), default=list, size=4),
        ),
    ]
