# Generated by Django 3.0 on 2020-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20200126_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='crew',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
