# Generated by Django 3.0 on 2020-02-08 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200127_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheetid', models.AutoField(primary_key=True, serialize=False)),
                ('payperiodid', models.CharField(max_length=8)),
                ('dayofweek', models.CharField(max_length=11)),
                ('crewid', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('seconds_paused', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('pause_time', models.TimeField(blank=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
