# Generated by Django 3.0 on 2020-02-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='crewid',
            new_name='userid',
        ),
    ]
