# Generated by Django 3.0 on 2020-02-09 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200209_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='seconds_paused',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
