# Generated by Django 3.0 on 2020-02-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20200209_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('payperiodid', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
            options={
                'db_table': 'payperiod',
                'ordering': ['-payperiodid'],
            },
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['crewid']},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-timesheetid']},
        ),
        migrations.AlterModelTable(
            name='crew',
            table='crew',
        ),
        migrations.AlterModelTable(
            name='timesheet',
            table='timesheet',
        ),
    ]
