# Generated by Django 3.0 on 2020-02-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20200209_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
