# Generated by Django 3.0 on 2020-02-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20200209_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
